const categoriesData = [
  {
    name: 'Electronics',
    description: 'Cutting-edge gadgets, smart devices, audio, and modern consumer tech.',
    icon: 'Tv',
    image: { url: 'https://images.unsplash.com/photo-1498049794561-7780e7231661?auto=format&fit=crop&w=600&q=80' },
    subcategories: ['Headphones', 'Smartwatches', 'Speakers', 'Cameras'],
    isFeatured: true,
  },
  {
    name: 'Mobiles',
    description: 'Latest 5G smartphones, flagship devices, and mobile accessories.',
    icon: 'Smartphone',
    image: { url: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=600&q=80' },
    subcategories: ['Flagship Smartphones', 'Budget Phones', 'Chargers', 'Cases'],
    isFeatured: true,
  },
  {
    name: 'Laptops',
    description: 'High-performance laptops, ultrabooks, gaming rigs, and computing accessories.',
    icon: 'Laptop',
    image: { url: 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=600&q=80' },
    subcategories: ['Gaming Laptops', 'Thin & Light', 'Workstations', 'Monitors'],
    isFeatured: true,
  },
  {
    name: 'Fashion',
    description: 'Trendy clothing, luxury apparel, and seasonal wardrobes for all ages.',
    icon: 'Shirt',
    image: { url: 'https://images.unsplash.com/photo-1445205170230-053b83016050?auto=format&fit=crop&w=600&q=80' },
    subcategories: ["Men's Wear", "Women's Wear", 'Casuals', 'Ethnic Wear'],
    isFeatured: true,
  },
  {
    name: "Men's Clothing",
    description: 'Shirts, t-shirts, denim, jackets, and formal attire for men.',
    icon: 'User',
    image: { url: 'https://images.unsplash.com/photo-1617137984095-74e4e5e3613f?auto=format&fit=crop&w=600&q=80' },
    subcategories: ['T-Shirts', 'Formal Shirts', 'Jeans', 'Jackets'],
    isFeatured: false,
  },
  {
    name: "Women's Clothing",
    description: 'Dresses, tops, ethnic wear, co-ord sets, and outerwear for women.',
    icon: 'Heart',
    image: { url: 'https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&w=600&q=80' },
    subcategories: ['Dresses', 'Tops & Tees', 'Ethnic Kurtis', 'Co-ord Sets'],
    isFeatured: true,
  },
  {
    name: 'Shoes',
    description: 'Athletic sneakers, running shoes, formal loafers, and casual kicks.',
    icon: 'Footprints',
    image: { url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=600&q=80' },
    subcategories: ['Sneakers', 'Running Shoes', 'Formal Shoes', 'Sandals'],
    isFeatured: true,
  },
  {
    name: 'Home & Kitchen',
    description: 'Modern cookware, aesthetic home decor, blenders, and furniture.',
    icon: 'Home',
    image: { url: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=600&q=80' },
    subcategories: ['Cookware', 'Coffee Makers', 'Lamps & Lighting', 'Bedding'],
    isFeatured: true,
  },
  {
    name: 'Beauty',
    description: 'Premium skincare, makeup essentials, haircare, and organic wellness.',
    icon: 'Sparkles',
    image: { url: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=600&q=80' },
    subcategories: ['Skincare', 'Fragrances', 'Haircare', 'Makeup'],
    isFeatured: true,
  },
  {
    name: 'Accessories',
    description: 'Luxury watches, polarized sunglasses, leather wallets, and belts.',
    icon: 'Watch',
    image: { url: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=600&q=80' },
    subcategories: ['Watches', 'Sunglasses', 'Wallets', 'Backpacks'],
    isFeatured: false,
  },
  {
    name: 'Sports',
    description: 'Fitness equipment, athletic gear, yoga essentials, and gym wear.',
    icon: 'Activity',
    image: { url: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=600&q=80' },
    subcategories: ['Gym Equipment', 'Yoga Mats', 'Sportswear', 'Hydration'],
    isFeatured: false,
  },
  {
    name: 'Books',
    description: 'Bestselling fiction, business masteries, self-help, and academic books.',
    icon: 'BookOpen',
    image: { url: 'https://images.unsplash.com/photo-1495446815901-a7297e633e8d?auto=format&fit=crop&w=600&q=80' },
    subcategories: ['Fiction', 'Business', 'Self-Help', 'Technology'],
    isFeatured: false,
  },
];

const couponsData = [
  {
    code: 'WELCOME50',
    discountType: 'percentage',
    discountValue: 15,
    minimumOrderAmount: 999,
    maximumDiscount: 500,
    startDate: new Date('2025-01-01'),
    expiryDate: new Date('2030-12-31'),
    usageLimit: 1000,
    isActive: true,
  },
  {
    code: 'FLAT200',
    discountType: 'fixed',
    discountValue: 200,
    minimumOrderAmount: 1499,
    maximumDiscount: 200,
    startDate: new Date('2025-01-01'),
    expiryDate: new Date('2030-12-31'),
    usageLimit: 500,
    isActive: true,
  },
  {
    code: 'SUPERDEAL',
    discountType: 'percentage',
    discountValue: 25,
    minimumOrderAmount: 2999,
    maximumDiscount: 1500,
    startDate: new Date('2025-01-01'),
    expiryDate: new Date('2030-12-31'),
    usageLimit: 250,
    isActive: true,
  },
  {
    code: 'FESTIVE10',
    discountType: 'percentage',
    discountValue: 10,
    minimumOrderAmount: 499,
    maximumDiscount: 300,
    startDate: new Date('2025-01-01'),
    expiryDate: new Date('2030-12-31'),
    usageLimit: 2000,
    isActive: true,
  },
];

const sampleProducts = [
  {
    name: 'Sony WH-1000XM5 Wireless Noise-Cancelling Headphones',
    categoryName: 'Electronics',
    subcategory: 'Headphones',
    brand: 'Sony',
    price: 29990,
    discountPrice: 24990,
    stock: 25,
    sku: 'SONY-WH1000XM5-BLK',
    shortDescription: 'Industry-leading noise cancelling with two processors and 8 microphones.',
    description: 'The Sony WH-1000XM5 wireless noise cancelling headphones rewrite the rules for distraction-free listening. Two processors control 8 microphones for unprecedented noise cancellation and exceptional call quality. With an Auto NC Optimizer, noise cancelling is automatically optimized based on your wearing conditions and environment.',
    images: [
      { url: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80' },
      { url: 'https://images.unsplash.com/photo-1484704849700-f032a568e944?auto=format&fit=crop&w=800&q=80' },
    ],
    specifications: [
      { key: 'Battery Life', value: 'Up to 30 hours' },
      { key: 'Connectivity', value: 'Bluetooth 5.2 & 3.5mm Jack' },
      { key: 'Noise Cancellation', value: 'Active Dual Processor ANC' },
      { key: 'Weight', value: '250 grams' },
    ],
    variants: {
      sizes: ['Standard'],
      colors: [
        { name: 'Midnight Black', hex: '#111827', inStock: true },
        { name: 'Silver White', hex: '#E5E7EB', inStock: true },
      ],
    },
    tags: ['headphones', 'wireless', 'noise-cancelling', 'sony', 'audio'],
    rating: 4.8,
    numReviews: 124,
    isFeatured: true,
    isBestseller: true,
    isNewArrival: false,
  },
  {
    name: 'Apple iPhone 15 Pro Max (256GB - Natural Titanium)',
    categoryName: 'Mobiles',
    subcategory: 'Flagship Smartphones',
    brand: 'Apple',
    price: 159900,
    discountPrice: 148900,
    stock: 14,
    sku: 'APPL-IPH15PM-256NT',
    shortDescription: 'Forged in titanium with groundbreaking A17 Pro chip and 48MP main camera.',
    description: 'iPhone 15 Pro Max is the first iPhone to feature an aerospace‑grade titanium design, using the same alloy that spacecraft use for missions to Mars. The A17 Pro chip brings gaming graphics to life like never before. The 48MP Main camera is more advanced than ever, capturing super‑high‑resolution photos with a new level of detail and color.',
    images: [
      { url: 'https://images.unsplash.com/photo-1695048133142-1a20484d2569?auto=format&fit=crop&w=800&q=80' },
      { url: 'https://images.unsplash.com/photo-1510557880182-3d4d3cba35a5?auto=format&fit=crop&w=800&q=80' },
    ],
    specifications: [
      { key: 'Display', value: '6.7-inch Super Retina XDR OLED 120Hz' },
      { key: 'Processor', value: 'Apple A17 Pro (3nm)' },
      { key: 'Storage', value: '256 GB' },
      { key: 'Camera', value: '48MP Triple Camera with 5x Optical Zoom' },
    ],
    variants: {
      sizes: ['256GB', '512GB', '1TB'],
      colors: [
        { name: 'Natural Titanium', hex: '#9CA3AF', inStock: true },
        { name: 'Blue Titanium', hex: '#1E3A8A', inStock: true },
        { name: 'Black Titanium', hex: '#1F2937', inStock: true },
      ],
    },
    tags: ['iphone', 'apple', 'smartphone', '5g', 'flagship'],
    rating: 4.9,
    numReviews: 245,
    isFeatured: true,
    isBestseller: true,
    isNewArrival: true,
  },
  {
    name: 'Samsung Galaxy S24 Ultra 5G (512GB - Titanium Gray)',
    categoryName: 'Mobiles',
    subcategory: 'Flagship Smartphones',
    brand: 'Samsung',
    price: 139999,
    discountPrice: 129999,
    stock: 18,
    sku: 'SAMS-S24U-512GRY',
    shortDescription: 'Galaxy AI is here. 200MP camera, Snapdragon 8 Gen 3, and built-in S-Pen.',
    description: 'Welcome to the era of mobile AI with the Samsung Galaxy S24 Ultra. Unleash whole new levels of creativity, productivity and possibility. Armor Aluminum frame, flat display with Corning Gorilla Armor, and built-in S Pen for seamless note-taking.',
    images: [
      { url: 'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?auto=format&fit=crop&w=800&q=80' },
      { url: 'https://images.unsplash.com/photo-1598327105666-5b89351aff97?auto=format&fit=crop&w=800&q=80' },
    ],
    specifications: [
      { key: 'Display', value: '6.8-inch Dynamic AMOLED 2X 120Hz' },
      { key: 'Processor', value: 'Snapdragon 8 Gen 3 for Galaxy' },
      { key: 'Battery', value: '5000 mAh 45W Fast Charging' },
      { key: 'S-Pen', value: 'Integrated S-Pen Included' },
    ],
    variants: {
      sizes: ['256GB', '512GB'],
      colors: [
        { name: 'Titanium Gray', hex: '#6B7280', inStock: true },
        { name: 'Titanium Violet', hex: '#7C3AED', inStock: true },
      ],
    },
    tags: ['samsung', 'galaxy', 'android', 'flagship', 'ai'],
    rating: 4.7,
    numReviews: 98,
    isFeatured: false,
    isBestseller: true,
    isNewArrival: true,
  },
  {
    name: 'Apple MacBook Pro 16-inch M3 Max (36GB RAM, 1TB SSD)',
    categoryName: 'Laptops',
    subcategory: 'Gaming Laptops',
    brand: 'Apple',
    price: 349900,
    discountPrice: 324900,
    stock: 9,
    sku: 'APPL-MBP16-M3MAX',
    shortDescription: 'The ultimate pro laptop. M3 Max chip with 16-core CPU and 40-core GPU.',
    description: 'MacBook Pro blasts forward with M3 Max, an extraordinarily advanced chip that brings immense performance and capabilities for extreme workflows. With industry-leading battery life up to 22 hours and a breathtaking Liquid Retina XDR display, it is a pro laptop without equal.',
    images: [
      { url: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=800&q=80' },
      { url: 'https://images.unsplash.com/photo-1611186871348-b1ce696e52c9?auto=format&fit=crop&w=800&q=80' },
    ],
    specifications: [
      { key: 'Processor', value: 'Apple M3 Max (16-core CPU, 40-core GPU)' },
      { key: 'Memory', value: '36GB Unified Memory' },
      { key: 'Storage', value: '1TB Ultra-fast PCIe SSD' },
      { key: 'Display', value: '16.2-inch Liquid Retina XDR (3456 x 2234)' },
    ],
    variants: {
      sizes: ['1TB', '2TB'],
      colors: [
        { name: 'Space Black', hex: '#1C1917', inStock: true },
        { name: 'Silver', hex: '#D1D5DB', inStock: true },
      ],
    },
    tags: ['macbook', 'apple', 'laptop', 'm3-max', 'workstation'],
    rating: 4.9,
    numReviews: 67,
    isFeatured: true,
    isBestseller: false,
    isNewArrival: true,
  },
  {
    name: 'Dell XPS 15 9530 OLED Touchscreen Ultrabook',
    categoryName: 'Laptops',
    subcategory: 'Thin & Light',
    brand: 'Dell',
    price: 189990,
    discountPrice: 169990,
    stock: 12,
    sku: 'DELL-XPS15-OLED',
    shortDescription: 'Intel Core i9 13th Gen, RTX 4070, 3.5K OLED InfinityEdge touch display.',
    description: 'Immerse yourself in content with stunning 3.5K OLED panels that provide high resolution, rich color and high contrast. The XPS 15 is the perfect balance of size and performance to fuel even more intensive creative projects with 13th Gen Intel Core processors and NVIDIA RTX 40-series graphics.',
    images: [
      { url: 'https://images.unsplash.com/photo-1593642632823-8f785ba67e45?auto=format&fit=crop&w=800&q=80' },
      { url: 'https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?auto=format&fit=crop&w=800&q=80' },
    ],
    specifications: [
      { key: 'Processor', value: 'Intel Core i9-13900H (14 Cores)' },
      { key: 'GPU', value: 'NVIDIA GeForce RTX 4070 (8GB GDDR6)' },
      { key: 'RAM', value: '32GB DDR5 4800MHz' },
      { key: 'Display', value: '15.6-inch 3.5K (3456x2160) OLED Touch' },
    ],
    variants: {
      sizes: ['16GB / 512GB', '32GB / 1TB'],
      colors: [
        { name: 'Platinum Silver', hex: '#9CA3AF', inStock: true },
      ],
    },
    tags: ['dell', 'xps', 'laptop', 'oled', 'creators'],
    rating: 4.6,
    numReviews: 42,
    isFeatured: false,
    isBestseller: false,
    isNewArrival: true,
  },
  {
    name: 'Nike Air Jordan 1 Retro High OG - Chicago Lost & Found',
    categoryName: 'Shoes',
    subcategory: 'Sneakers',
    brand: 'Nike',
    price: 18995,
    discountPrice: 15495,
    stock: 20,
    sku: 'NIKE-AJ1-LOSTFOUND',
    shortDescription: 'The iconic 1985 silhouette reimagined with vintage accents and premium leather.',
    description: 'The Air Jordan 1 Retro High OG brings back the coveted Chicago colorway with a vintage aesthetic. Featuring premium leather in signature varsity red, sail, and black, alongside aged cracked leather details that celebrate sneaker history.',
    images: [
      { url: 'https://images.unsplash.com/photo-1552346154-21d32810aba3?auto=format&fit=crop&w=800&q=80' },
      { url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80' },
    ],
    specifications: [
      { key: 'Material', value: 'Genuine Full-Grain Leather' },
      { key: 'Cushioning', value: 'Encapsulated Nike Air-Sole unit' },
      { key: 'Outsole', value: 'Solid Rubber with Pivot Circle' },
    ],
    variants: {
      sizes: ['UK 7', 'UK 8', 'UK 9', 'UK 10', 'UK 11'],
      colors: [
        { name: 'Varsity Red / White / Black', hex: '#DC2626', inStock: true },
      ],
    },
    tags: ['shoes', 'sneakers', 'nike', 'jordan', 'streetwear'],
    rating: 4.9,
    numReviews: 189,
    isFeatured: true,
    isBestseller: true,
    isNewArrival: false,
  },
  {
    name: 'Adidas Ultraboost Light Running Shoes',
    categoryName: 'Shoes',
    subcategory: 'Running Shoes',
    brand: 'Adidas',
    price: 16999,
    discountPrice: 12499,
    stock: 35,
    sku: 'ADID-UB-LIGHT-WHT',
    shortDescription: 'Our lightest Ultraboost ever made with 30% lighter Light BOOST material.',
    description: 'Experience epic energy return with the new Ultraboost Light, our lightest Ultraboost ever. The magic lies in the Light BOOST midsole, a new generation of adidas BOOST. Its unique molecule design achieves the lightest BOOST foam to date.',
    images: [
      { url: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80' },
      { url: 'https://images.unsplash.com/photo-1608231387042-66d1773070a5?auto=format&fit=crop&w=800&q=80' },
    ],
    specifications: [
      { key: 'Upper', value: 'Primeknit+ textile upper' },
      { key: 'Midsole', value: 'Light BOOST midsole' },
      { key: 'Drop', value: '10 mm (heel: 30 mm / forefoot: 20 mm)' },
    ],
    variants: {
      sizes: ['UK 6', 'UK 7', 'UK 8', 'UK 9', 'UK 10'],
      colors: [
        { name: 'Cloud White / Core Black', hex: '#F3F4F6', inStock: true },
        { name: 'Core Black / Solar Red', hex: '#111827', inStock: true },
      ],
    },
    tags: ['adidas', 'ultraboost', 'running', 'marathon', 'shoes'],
    rating: 4.7,
    numReviews: 76,
    isFeatured: false,
    isBestseller: true,
    isNewArrival: true,
  },
  {
    name: 'Levi’s Men’s 511 Slim Fit Stretch Denim Jeans',
    categoryName: "Men's Clothing",
    subcategory: 'Jeans',
    brand: "Levi's",
    price: 4599,
    discountPrice: 2999,
    stock: 50,
    sku: 'LEVI-511-DARKIND',
    shortDescription: 'Modern slim-fit jeans with room to move, crafted in sustainable stretch cotton.',
    description: 'A modern slim with room to move, the 511 Slim Fit Stretch Jeans are a classic since right now. These jeans sit below the waist with a slim fit from hip to ankle. Crafted with Levi’s Flex: advanced stretch technology engineered to deliver maximum flex and comfort.',
    images: [
      { url: 'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?auto=format&fit=crop&w=800&q=80' },
      { url: 'https://images.unsplash.com/photo-1542272604-780c96856592?auto=format&fit=crop&w=800&q=80' },
    ],
    specifications: [
      { key: 'Material', value: '99% Cotton, 1% Elastane' },
      { key: 'Closure', value: 'Zip Fly with Button Closure' },
      { key: 'Fit', value: 'Slim fit from hip to ankle' },
    ],
    variants: {
      sizes: ['30', '32', '34', '36', '38'],
      colors: [
        { name: 'Dark Indigo Rinse', hex: '#1E3A8A', inStock: true },
        { name: 'Washed Black', hex: '#1F2937', inStock: true },
      ],
    },
    tags: ['levis', 'jeans', 'denim', 'menswear', 'slim-fit'],
    rating: 4.5,
    numReviews: 95,
    isFeatured: false,
    isBestseller: true,
    isNewArrival: false,
  },
  {
    name: 'Zara Tailored Textured Linen Blend Blazer',
    categoryName: 'Fashion',
    subcategory: 'Jackets',
    brand: 'Zara',
    price: 8990,
    discountPrice: 6490,
    stock: 22,
    sku: 'ZARA-BLZ-LINEN',
    shortDescription: 'Structured notch-lapel blazer with breathable summer linen construction.',
    description: 'Elevate your summer wardrobe with this sophisticated textured linen blazer. Features notch lapels, flap hip pockets, chest welt pocket, and back vent. Breathable, lightweight, and meticulously tailored for any upscale brunch or evening event.',
    images: [
      { url: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=800&q=80' },
      { url: 'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?auto=format&fit=crop&w=800&q=80' },
    ],
    specifications: [
      { key: 'Material', value: '55% Linen, 45% Cotton' },
      { key: 'Lining', value: '100% Viscose Acetate' },
      { key: 'Care', value: 'Dry Clean Only' },
    ],
    variants: {
      sizes: ['S', 'M', 'L', 'XL'],
      colors: [
        { name: 'Sand Beige', hex: '#D7CCC8', inStock: true },
        { name: 'Navy Blue', hex: '#0F172A', inStock: true },
      ],
    },
    tags: ['zara', 'blazer', 'linen', 'formal', 'mens-fashion'],
    rating: 4.6,
    numReviews: 38,
    isFeatured: true,
    isBestseller: false,
    isNewArrival: true,
  },
  {
    name: 'H&M Floral Print Tiered Maxi Dress',
    categoryName: "Women's Clothing",
    subcategory: 'Dresses',
    brand: 'H&M',
    price: 3999,
    discountPrice: 2499,
    stock: 40,
    sku: 'HM-FLORAL-MAXI',
    shortDescription: 'Flowy ankle-length dress in airy woven fabric with tiered ruffled hem.',
    description: 'Ankle-length dress in an airy, woven fabric with a romantic floral motif. V-neckline with delicate ties at front, three-quarter balloon sleeves with elasticized cuffs, and a gently tiered skirt that moves gracefully with every step.',
    images: [
      { url: 'https://images.unsplash.com/photo-1496747611176-843222e1e57c?auto=format&fit=crop&w=800&q=80' },
      { url: 'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?auto=format&fit=crop&w=800&q=80' },
    ],
    specifications: [
      { key: 'Material', value: '100% Recycled Polyester' },
      { key: 'Length', value: 'Maxi / Ankle-length' },
      { key: 'Care', value: 'Machine wash 30°C' },
    ],
    variants: {
      sizes: ['XS', 'S', 'M', 'L', 'XL'],
      colors: [
        { name: 'Sage Green Floral', hex: '#6EE7B7', inStock: true },
        { name: 'Sunset Peach', hex: '#FDBA74', inStock: true },
      ],
    },
    tags: ['dress', 'floral', 'summer', 'womens-wear', 'hm'],
    rating: 4.8,
    numReviews: 112,
    isFeatured: true,
    isBestseller: true,
    isNewArrival: true,
  },
  {
    name: 'Nespresso VertuoPlus Coffee & Espresso Machine',
    categoryName: 'Home & Kitchen',
    subcategory: 'Coffee Makers',
    brand: 'Nespresso',
    price: 19999,
    discountPrice: 15999,
    stock: 15,
    sku: 'NESP-VERTUO-PLUS',
    shortDescription: 'Centrifusion technology brews 5 cup sizes with single-touch convenience.',
    description: 'Nespresso VertuoPlus offers freshly brewed coffee with crema as well as delicious, authentic espresso. The machine conveniently makes 5 cup sizes: 14oz Alto, 8oz Coffee, 5oz Gran Lungo, 2.7oz Double Espresso, and 1.35oz Espresso, all at the touch of a button.',
    images: [
      { url: 'https://images.unsplash.com/photo-1517668808822-9ebb02f2a0e6?auto=format&fit=crop&w=800&q=80' },
      { url: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=800&q=80' },
    ],
    specifications: [
      { key: 'Water Tank Capacity', value: '1.7 Litres moveable tank' },
      { key: 'Heat-up Time', value: '20-25 seconds' },
      { key: 'Auto-shutoff', value: 'After 9 minutes of inactivity' },
    ],
    variants: {
      sizes: ['Standard'],
      colors: [
        { name: 'Piano Black', hex: '#111827', inStock: true },
        { name: 'Matte Titanium', hex: '#6B7280', inStock: true },
      ],
    },
    tags: ['coffee', 'espresso', 'kitchen', 'nespresso', 'appliances'],
    rating: 4.7,
    numReviews: 64,
    isFeatured: true,
    isBestseller: false,
    isNewArrival: false,
  },
  {
    name: 'Le Creuset Enameled Cast Iron Signature Round Dutch Oven (5.5 Qt)',
    categoryName: 'Home & Kitchen',
    subcategory: 'Cookware',
    brand: 'Le Creuset',
    price: 36500,
    discountPrice: 31500,
    stock: 8,
    sku: 'LECR-DUTCH-55QT',
    shortDescription: 'The gold standard in enameled cast iron cookware, handcrafted in France since 1925.',
    description: 'The iconic Le Creuset Dutch oven is indispensable in the kitchens of home cooks and professional chefs alike. Expertly crafted from enameled cast iron, the everyday versatility of the Dutch oven makes it ideal for everything from slow-cooking and braising to roasting, baking, frying and more.',
    images: [
      { url: 'https://images.unsplash.com/photo-1584990347449-39908cf6b41d?auto=format&fit=crop&w=800&q=80' },
      { url: 'https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=800&q=80' },
    ],
    specifications: [
      { key: 'Capacity', value: '5.5 Quarts (5.3 Litres)' },
      { key: 'Heat Source', value: 'Gas, Electric, Ceramic, Halogen, Induction, Oven' },
      { key: 'Origin', value: 'Made in France' },
    ],
    variants: {
      sizes: ['4.5 Qt', '5.5 Qt', '7.25 Qt'],
      colors: [
        { name: 'Cerise Red', hex: '#DC2626', inStock: true },
        { name: 'Marseille Blue', hex: '#2563EB', inStock: true },
        { name: 'Flame Orange', hex: '#EA580C', inStock: true },
      ],
    },
    tags: ['cookware', 'dutch-oven', 'cast-iron', 'kitchen', 'luxury'],
    rating: 5.0,
    numReviews: 48,
    isFeatured: true,
    isBestseller: false,
    isNewArrival: false,
  },
  {
    name: 'Estée Lauder Advanced Night Repair Synchronized Multi-Recovery Serum',
    categoryName: 'Beauty',
    subcategory: 'Skincare',
    brand: 'Estée Lauder',
    price: 8900,
    discountPrice: 7490,
    stock: 45,
    sku: 'ESTE-ANR-50ML',
    shortDescription: '#1 luxury serum in the world. Reduces the look of multiple signs of aging.',
    description: 'Harness the restorative power of night. This deep- and fast-penetrating face serum, with our exclusive Chronolux Power Signal Technology, boosts skin’s natural renewal and collagen production. Skin feels firmer, looks radiant, hydrated, and full of life.',
    images: [
      { url: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=800&q=80' },
      { url: 'https://images.unsplash.com/photo-1608248597359-0f2c424a18fa?auto=format&fit=crop&w=800&q=80' },
    ],
    specifications: [
      { key: 'Volume', value: '50 ml / 1.7 oz' },
      { key: 'Skin Type', value: 'All skin types, dermatologist tested' },
      { key: 'Formulation', value: 'Oil-free, non-comedogenic serum' },
    ],
    variants: {
      sizes: ['30ml', '50ml', '75ml'],
      colors: [],
    },
    tags: ['serum', 'skincare', 'beauty', 'anti-aging', 'esteelauder'],
    rating: 4.8,
    numReviews: 210,
    isFeatured: true,
    isBestseller: true,
    isNewArrival: false,
  },
  {
    name: 'Dior Sauvage Eau de Parfum (100ml)',
    categoryName: 'Beauty',
    subcategory: 'Fragrances',
    brand: 'Dior',
    price: 13500,
    discountPrice: 11999,
    stock: 30,
    sku: 'DIOR-SAUVAGE-100ML',
    shortDescription: 'Raw, noble, and magnetic fragrance with Calabrian bergamot and spicy ambroxan.',
    description: 'A powerfully fresh creation, Sauvage Eau de Parfum is inspired by the desert in the magical hour of twilight. Mixed with the coolness of the night, the burning desert air exudes profound scents. Sensual notes of Papua New Guinean vanilla absolute wrap a mysterious amber wood trail.',
    images: [
      { url: 'https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?auto=format&fit=crop&w=800&q=80' },
      { url: 'https://images.unsplash.com/photo-1547887537-6158d64c35b3?auto=format&fit=crop&w=800&q=80' },
    ],
    specifications: [
      { key: 'Fragrance Family', value: 'Warm & Spicy Citrus Woody' },
      { key: 'Key Notes', value: 'Reggio Bergamot, Sichuan Pepper, Ambroxan, Vanilla' },
      { key: 'Volume', value: '100 ml / 3.4 oz' },
    ],
    variants: {
      sizes: ['60ml', '100ml', '200ml'],
      colors: [],
    },
    tags: ['perfume', 'dior', 'fragrance', 'luxury', 'cologne'],
    rating: 4.9,
    numReviews: 310,
    isFeatured: false,
    isBestseller: true,
    isNewArrival: false,
  },
  {
    name: 'Seiko Prospex Automatic Diver 200m "King Turtle" Watch',
    categoryName: 'Accessories',
    subcategory: 'Watches',
    brand: 'Seiko',
    price: 49500,
    discountPrice: 42500,
    stock: 10,
    sku: 'SEIK-TURTLE-SRPE03',
    shortDescription: 'Sapphire crystal, ceramic bezel, 4R36 automatic movement with 200m water resistance.',
    description: 'The Seiko Prospex SRPE03 King Turtle is upgraded with a scratch-resistant sapphire crystal featuring an anti-reflective coating on the inner surface and a magnifying day/date cyclops. The ceramic unidirectional bezel is durable, sharp, and iconic.',
    images: [
      { url: 'https://images.unsplash.com/photo-1524805444758-089113d48a6d?auto=format&fit=crop&w=800&q=80' },
      { url: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=800&q=80' },
    ],
    specifications: [
      { key: 'Movement', value: 'Seiko 4R36 Automatic (41-hour power reserve)' },
      { key: 'Case Diameter', value: '45.0 mm' },
      { key: 'Crystal', value: 'Sapphire with Magnifier Lens' },
      { key: 'Water Resistance', value: '200 meters / 660 feet' },
    ],
    variants: {
      sizes: ['45mm'],
      colors: [
        { name: 'Black Waffle Dial', hex: '#111827', inStock: true },
      ],
    },
    tags: ['watch', 'seiko', 'automatic', 'dive-watch', 'accessories'],
    rating: 4.8,
    numReviews: 54,
    isFeatured: false,
    isBestseller: false,
    isNewArrival: true,
  },
  {
    name: 'Ray-Ban Classic Polarized Aviator Sunglasses',
    categoryName: 'Accessories',
    subcategory: 'Sunglasses',
    brand: 'Ray-Ban',
    price: 11290,
    discountPrice: 8990,
    stock: 35,
    sku: 'RAYB-RB3025-POL',
    shortDescription: 'Timeless tear-drop metal frame with crystal green polarized G-15 lenses.',
    description: 'Currently one of the most iconic sunglass models in the world, Ray-Ban Aviator Classic sunglasses were originally designed for U.S. aviators in 1937. Aviator Classic sunglasses are a timeless model that combines great aviator styling with exceptional quality, performance and comfort.',
    images: [
      { url: 'https://images.unsplash.com/photo-1572635196237-14b3f281503f?auto=format&fit=crop&w=800&q=80' },
      { url: 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?auto=format&fit=crop&w=800&q=80' },
    ],
    specifications: [
      { key: 'Frame Material', value: 'Lightweight Arista Gold Metal' },
      { key: 'Lens Treatment', value: 'Polarized G-15 Green Crystal' },
      { key: 'UV Protection', value: '100% UVA/UVB protection' },
    ],
    variants: {
      sizes: ['55mm (Small)', '58mm (Standard)', '62mm (Large)'],
      colors: [
        { name: 'Gold / G-15 Green', hex: '#EAB308', inStock: true },
        { name: 'Black / Polarized Grey', hex: '#1F2937', inStock: true },
      ],
    },
    tags: ['sunglasses', 'ray-ban', 'aviator', 'polarized', 'fashion'],
    rating: 4.7,
    numReviews: 142,
    isFeatured: true,
    isBestseller: true,
    isNewArrival: false,
  },
  {
    name: 'Bowflex SelectTech 552 Adjustable Dumbbells (Pair)',
    categoryName: 'Sports',
    subcategory: 'Gym Equipment',
    brand: 'Bowflex',
    price: 38990,
    discountPrice: 32990,
    stock: 14,
    sku: 'BOWF-552-PAIR',
    shortDescription: 'Replaces 15 sets of weights in a compact dial system adjusting from 5 to 52.5 lbs.',
    description: 'With just the turn of a dial, you can automatically change your resistance from 5 lbs all the way up to 52.5 lbs of weight. No more picking up 30 different dumbbells to get the results you want; these adjustable dumbbells replace 15 sets of weights.',
    images: [
      { url: 'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?auto=format&fit=crop&w=800&q=80' },
      { url: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=800&q=80' },
    ],
    specifications: [
      { key: 'Weight Range', value: '5 to 52.5 lbs (2.3 to 23.8 kg) per dumbbell' },
      { key: 'Weight Settings', value: '15 unique increments' },
      { key: 'Warranty', value: '2-Year Manufacturer Warranty' },
    ],
    variants: {
      sizes: ['Pair (5-52.5 lbs)'],
      colors: [
        { name: 'Black & Red', hex: '#DC2626', inStock: true },
      ],
    },
    tags: ['fitness', 'dumbbells', 'bowflex', 'home-gym', 'workout'],
    rating: 4.8,
    numReviews: 73,
    isFeatured: false,
    isBestseller: false,
    isNewArrival: true,
  },
  {
    name: 'Manduka PRO Yoga & Pilates Mat (6mm High Density)',
    categoryName: 'Sports',
    subcategory: 'Yoga Mats',
    brand: 'Manduka',
    price: 11500,
    discountPrice: 9499,
    stock: 28,
    sku: 'MAND-PRO-6MM',
    shortDescription: 'The #1 mat recommended by teachers worldwide, backed by lifetime warranty.',
    description: 'An ultra-dense and spacious performance yoga mat that has unmatched comfort and cushioning. The Manduka PRO will never wear out, guaranteed. Dense cushioning protects joints while providing a stable, grounded foundation during any practice.',
    images: [
      { url: 'https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?auto=format&fit=crop&w=800&q=80' },
      { url: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?auto=format&fit=crop&w=800&q=80' },
    ],
    specifications: [
      { key: 'Dimensions', value: '71" x 26" (180cm x 66cm)' },
      { key: 'Thickness', value: '6 mm ultra-dense cushion' },
      { key: 'Certification', value: 'OEKO-TEX certified non-toxic' },
    ],
    variants: {
      sizes: ['Standard 71"', 'Long 85"'],
      colors: [
        { name: 'Black Sage', hex: '#064E3B', inStock: true },
        { name: 'Midnight Purple', hex: '#581C87', inStock: true },
      ],
    },
    tags: ['yoga', 'manduka', 'fitness', 'pilates', 'wellness'],
    rating: 4.9,
    numReviews: 88,
    isFeatured: false,
    isBestseller: true,
    isNewArrival: false,
  },
  {
    name: 'Atomic Habits by James Clear (Hardcover Collector’s Edition)',
    categoryName: 'Books',
    subcategory: 'Self-Help',
    brand: 'Penguin Random House',
    price: 1299,
    discountPrice: 799,
    stock: 120,
    sku: 'BOOK-ATOMIC-HABITS',
    shortDescription: 'Over 15 million copies sold. An Easy & Proven Way to Build Good Habits & Break Bad Ones.',
    description: 'No matter your goals, Atomic Habits offers a proven framework for improving—every day. James Clear, one of the world’s leading experts on habit formation, reveals practical strategies that will teach you exactly how to form good habits, break bad ones, and master the tiny behaviors that lead to remarkable results.',
    images: [
      { url: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?auto=format&fit=crop&w=800&q=80' },
      { url: 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?auto=format&fit=crop&w=800&q=80' },
    ],
    specifications: [
      { key: 'Format', value: 'Hardcover, 320 pages' },
      { key: 'Publisher', value: 'Avery (Penguin Group)' },
      { key: 'Language', value: 'English' },
      { key: 'ISBN-13', value: '978-0735211292' },
    ],
    variants: {
      sizes: ['Hardcover', 'Paperback', 'Kindle Edition'],
      colors: [],
    },
    tags: ['books', 'self-help', 'productivity', 'habits', 'bestseller'],
    rating: 4.9,
    numReviews: 450,
    isFeatured: true,
    isBestseller: true,
    isNewArrival: false,
  },
  {
    name: 'Sony PlayStation 5 Slim Digital Console (1TB SSD)',
    categoryName: 'Electronics',
    subcategory: 'Cameras',
    brand: 'Sony',
    price: 44990,
    discountPrice: 39990,
    stock: 16,
    sku: 'SONY-PS5-SLIM-DIG',
    shortDescription: 'Experience lightning fast loading with an ultra-high speed SSD and ray tracing graphics.',
    description: 'The PS5 Digital Edition unleashes new gaming possibilities that you never anticipated. Experience lightning-fast loading with an ultra-high speed SSD, deeper immersion with support for haptic feedback, adaptive triggers, and 3D Audio, and an all-new generation of incredible PlayStation games.',
    images: [
      { url: 'https://images.unsplash.com/photo-1606813907291-d86efa9b94db?auto=format&fit=crop&w=800&q=80' },
      { url: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?auto=format&fit=crop&w=800&q=80' },
    ],
    specifications: [
      { key: 'Processor', value: 'AMD Zen 2 x86-64 (8 cores / 16 threads)' },
      { key: 'Graphics', value: 'AMD Radeon RDNA 2-based graphics engine' },
      { key: 'Storage', value: '1TB Custom High-Speed NVMe SSD' },
      { key: 'Audio', value: 'Tempest 3D AudioTech' },
    ],
    variants: {
      sizes: ['1TB Digital', '1TB Disc Edition'],
      colors: [
        { name: 'Glacier White', hex: '#F9FAFB', inStock: true },
      ],
    },
    tags: ['gaming', 'playstation', 'ps5', 'sony', 'console'],
    rating: 4.9,
    numReviews: 168,
    isFeatured: true,
    isBestseller: true,
    isNewArrival: true,
  },
  {
    name: 'Apple Watch Series 9 GPS + Cellular (45mm Starlight Aluminum)',
    categoryName: 'Electronics',
    subcategory: 'Smartwatches',
    brand: 'Apple',
    price: 54900,
    discountPrice: 48900,
    stock: 22,
    sku: 'APPL-WAT9-45STAR',
    shortDescription: 'Smarter, brighter, mightier. Introducing the double tap gesture and S9 SiP.',
    description: 'Apple Watch Series 9 helps you stay connected, active, healthy, and safe. Featuring the S9 SiP, which enables a superbright display and a magic new way to quickly and easily interact with your Apple Watch without touching the screen.',
    images: [
      { url: 'https://images.unsplash.com/photo-1546868871-7041f2a55e12?auto=format&fit=crop&w=800&q=80' },
      { url: 'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?auto=format&fit=crop&w=800&q=80' },
    ],
    specifications: [
      { key: 'Case Size', value: '45mm Starlight Aluminum' },
      { key: 'Display', value: 'Always-On Retina display up to 2000 nits' },
      { key: 'Sensors', value: 'Blood Oxygen, ECG, Temperature sensing, Fall Detection' },
    ],
    variants: {
      sizes: ['41mm', '45mm'],
      colors: [
        { name: 'Starlight', hex: '#F5F5F4', inStock: true },
        { name: 'Midnight', hex: '#0F172A', inStock: true },
        { name: 'Silver', hex: '#E5E7EB', inStock: true },
      ],
    },
    tags: ['apple-watch', 'smartwatch', 'fitness', 'wearables', 'apple'],
    rating: 4.8,
    numReviews: 135,
    isFeatured: true,
    isBestseller: true,
    isNewArrival: false,
  },
];

module.exports = {
  categoriesData,
  couponsData,
  sampleProducts,
};
